import java.util.ArrayList;

public class Question_44 {
    // given a string , write a program to return all its subsequences in an arraylist. A String is a subsequence of a given String that is generated by deleting some character of a 
    // given string without changing its order 


    static ArrayList<String> getss(String s){

        ArrayList <String> ans = new ArrayList<>();

        if(s.length() == 0) {
            ans.add(" ");
            return ans;
        }

        char curr = s.charAt(0);
        ArrayList<String> smallAns = getss(s.substring(1));

        for(String ss: smallAns){
            ans.add(ss);
            ans.add(curr + ss);
        }

        return ans;
    }

    public static void main(String[] args) {
        
        ArrayList<String> ans = getss("abc");
        for(String ss : ans){
            System.out.println(ss);
        }
    }
}
